import { Fraction } from "../fractions"
import { Operation } from "../types"

/**
 * A practice problem for the user to solve. Questions are generated by the
 * desired generator function selected by the user.
 *
 * @see FractionGenerator
 */
export type Question =
    | Fraction
    | {
        operation: Operation
        left: Fraction
        right: Question
    }
    ;;

export function solveQuestion(q: Question, simplify = false): Fraction {
    if (q instanceof Fraction) {
        return simplify ? q.simplify() : q
    }

    throw new Error("Not implemented")
    const { operaton, left, right } = q

    switch (operaton) {
        // case Operation.Addition: return solveQuestion(left, simplify) + solveQuestion(right, simplify)
    }
}
