# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "*.md"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # set up node
      - name: Use Node.js v14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # cache node_modules
      - uses: actions/cache@v2
        id: cache-modules
        with:
          path: |
            **/node_modules
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      # install dependencies
      - name: yarn install (cache miss)
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --immutable --check-cache

      - name: yarn install (cache hit)
        if: steps.cache-modules.outputs.cache-hit == 'true'
        run: yarn --immutable

      # run TSC without outputting files or bundling. Type checking only
      - run: yarn typecheck

      # build app, also runs linter
      - run: yarn build

      # Test & publish coverage
      - name: Test & publish coverage to CodeClimate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverage
