name: Lint and Typecheck

on:
  push:
    paths-ignore:
      - "*.md"
    branches-ignore:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
    branches-ignore:
      - master

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # set up node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # cache node_modules
      - uses: actions/cache@v2
        id: cache-modules
        with:
          path: |
            **/node_modules
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      # install dependencies
      - name: yarn install (cache miss)
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --immutable --check-cache

      - name: yarn install (cache hit)
        if: steps.cache-modules.outputs.cache-hit == 'true'
        run: yarn --immutable

      # check for style violations
      - run: yarn lint

      # run TSC without outputting files or bundling. Type checking only
      - run: yarn typecheck
